### ISSUE TITLE
how to run this application

### ISSUE THREAD

**Issue by saipavan9** [ColoradoSchoolOfMines/blockmrs#1]
Please update the Readme file on how to run the application to see the output. It will be very difficult for people to understand and run the application

**Comment by jackrosenthal** [comment]
Hi @saipavan9 ,

This was a hackathon project, and most definitely **is not suited for production use as is**. Hence, I don't really want to update the README; as it would imply we recommend using the application. However, if you're curious to see what it looks like, you'll need:

1. An IPFS cluster running on your machine
2. Python 3.6+ and TurboGears 2.3 development tools running on your machine

Then, just follow the TurboGears documentation to ``setup-app`` and ``serve``:
https://turbogears.readthedocs.io/en/latest/turbogears/gearbox.html#setup-app

Let me know if you run into any issues.
